AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False # as we don't need F.C LAYER only need CONV LAYER
EPOCHS: 51
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01